### ISSUE TITLE
Unable to install app in android 12

### ISSUE THREAD

**Issue by kavi7996** [Estimote/Android-Proximity-SDK#107]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [1.0.5]

**Android devices affected:** [pixel 4a]

**Android OS version affected:** [Android OS version 12]

**Beacon hardware version:** [] 

## Description

Hi,
I have faced issue in app installation in android 12. I got below error while trying to install the app. can you please help me with it.

10:18 AM	Failed to commit install session 432218487 with command cmd package install-commit 432218487. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl432218487.tmp/base.apk (at Binary XML file line #461): com.estimote.proximity_sdk.api.TriggerBroadcastReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

**Comment by moalfa** [comment]
To solve the problem you can extend the receiver Tag from the library proximity-sdk-x.x.x  

Go to `AndroidManifest.xml` and add a receiver 

```
 <application>
 //....

  <receiver
              android:name="com.estimote.proximity_sdk.api.TriggerBroadcastReceiver"
              android:exported="true"
              tools:node="merge" />

</application>
```

**Comment by Shailevy** [comment]
But if you scan using the estimote core SDK you will crash. So this workaround is too limited

java.lang.IllegalArgumentException: com.#####: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.SystemAlarmManager.setAlarm(SystemAlarmManager.java:32)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.NougatScanScheduler.scheduleForegroundAlarm(NougatScanScheduler.java:294)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.NougatScanScheduler.scheduleAlarm(NougatScanScheduler.java:271)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.NougatScanScheduler.access$400(NougatScanScheduler.java:29)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.NougatScanScheduler$1.execute(NougatScanScheduler.java:152)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at com.estimote.coresdk.scanning.scheduling.ScanCommandBuffer$2.run(ScanCommandBuffer.java:54)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
03-13 11:26:08.407 15139 15307 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
