### ISSUE TITLE
Exception No interface method getDeviceIdToProximityAttachmentMapping

### ISSUE THREAD

**Issue by MarcoManca** [Estimote/Android-Proximity-SDK#20]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** implementation 'com.estimote:proximity-sdk:0.2.2'

**Android devices affected:** Huawei P8 lite 2017

**Android OS version affected:** Android 7

**Beacon hardware version:** F3.3

## Description

hi, 
I'm developing an application with estimote proximity sdk.
I just copied and pasted the example described here: https://github.com/Estimote/Android-Proximity-SDK
When the ProximityObserver starts it throws the following exception:

java.lang.NoSuchMethodError: No interface method getDeviceIdToProximityAttachmentMapping(Ljava/util/List;)Lio/reactivex/Single; in class Lcom/estimote/internal_plugins_api/cloud/proximity/ProximityCloud; or its super classes (declaration of 'com.estimote.internal_plugins_api.cloud.proximity.ProximityCloud' appears in /data/app/hiis.isti.cnr.it.estimoteproximitydelegate-2/split_lib_dependencies_apk.apk)

java.lang.NoSuchMethodError: No interface method getDeviceIdToProximityAttachmentMapping(Ljava/util/List;)Lio/reactivex/Single; in class Lcom/estimote/internal_plugins_api/cloud/proximity/ProximityCloud; or its super classes (declaration of 'com.estimote.internal_plugins_api.cloud.proximity.ProximityCloud' appears in /data/app/hiis.isti.cnr.it.estimotedelegate-2/split_lib_dependencies_apk.apk)
                      at com.estimote.proximity_sdk.proximity.mapping.CloudOnlyAttachmentMappingProvider.provideAttachmentMapping(CloudOnlyAttachmentMappingProvider.kt:11)
                      at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase.run(ProximityObservationUseCase.kt:23)
                      at com.estimote.proximity_sdk.proximity.EstimoteProximityObserver.start(EstimoteProximityObserver.kt:28)
                      at com.estimote.proximity_sdk.telemetry_reporter.TelemetryProximityObserverWrapper.start(TelemetryProximityObserverWrapper.kt:31)
                      at hiis.isti.cnr.it.estimotedelegate.MainActivity$4.invoke(MainActivity.java:80)
                      at hiis.isti.cnr.it.estimotedelegate.MainActivity$4.invoke(MainActivity.java:77)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard$notifyCallbacks$1.accept(EstimoteRequirementsWizard.kt:43)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard$notifyCallbacks$1.accept(EstimoteRequirementsWizard.kt:10)
                      at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
                      at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
                      at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                      at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
                      at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
                      at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                      at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
                      at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                      at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
                      at io.reactivex.Single.subscribe(Single.java:2707)
                      at io.reactivex.Single.subscribe(Single.java:2693)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard.notifyCallbacks(EstimoteRequirementsWizard.kt:41)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard.fulfillRequirements(EstimoteRequirementsWizard.kt:22)
                      at hiis.isti.cnr.it.estimotedelegate.MainActivity.onCreate(MainActivity.java:77)
                      at android.app.Activity.performCreate(Activity.java:6910)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Can anyone knows which is the problem?

Thanks

Marco

**Comment by pawelDylag** [comment]
Hey @MarcoManca 

It's my super dumb fault, sorry for that :)
The version `0.2.3` should have it working :) 
`implementation 'com.estimote:proximity-sdk:0.2.3'`

Regards, 
Paweł

**Comment by MarcoManca** [comment]
Excellent, now it works!

Thank you
