### ISSUE TITLE
Crash when activating service?

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#21]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** `0.2.3`

**Android devices affected:** Wiko Fever

**Android OS version affected:** `Marshmallow 6.0`

**Beacon hardware version:** F3.3

## Description
On an old smartphone running on Android 6.0, I have troubles to receive a notification when I enter an area defined by some beacons. It's working fine with a Samsung Galaxy S7 on Android 7.0 by the way.

I don't know exactly when this happens because I'm activating Bluetooth on the device, in order to register and unregister the service in the background. And immediately after, I should receive a notification from one signal (the onEnter event should make a http call and the remote server activate should send a push notification). 

Here's a snippet and the stacktrace

## Additional information
Snippet
```
Notification notification = new Notification.Builder(context)
                .setContentTitle("Title")
                .setContentText("Monitoring…")
                .addAction(android.R.drawable.stat_sys_data_bluetooth, "Configure", pendingIntent)
                .setSmallIcon(R.drawable.ic_notification)
                .build();

        ProximityObserverBuilder builder = new ProximityObserverBuilder(context, new EstimoteCloudCredentials(appId, appToken));
        proximityObserver = builder
                .withBalancedPowerMode()
                .withScannerInForegroundService(notification)
                .withOnErrorAction(errorAction)
                .build();
```

Stacktrace:
```
#0. Crashed: main
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3226)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

--

Fatal Exception: java.lang.RuntimeException: Unable to start service com.estimote.scanning_sdk.packet_provider.service.PacketProviderWrapperService@703325b with null: java.lang.IllegalArgumentException: null notification
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3226)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Caused by java.lang.IllegalArgumentException: null notification
       at android.os.Parcel.readException(Parcel.java:1603)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:3876)
       at android.app.Service.startForeground(Service.java:653)
       at com.estimote.scanning_sdk.packet_provider.service.PacketProviderWrapperService.showNotification(PacketProviderWrapperService.kt:73)
       at com.estimote.scanning_sdk.packet_provider.service.PacketProviderWrapperService.onStartCommand(PacketProviderWrapperService.kt:32)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3209)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

#0. Crashed: main
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3226)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

#1. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#2. HeapTaskDaemon
       at dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java)
       at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:443)
       at java.lang.Thread.run(Thread.java:818)

#3. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#4. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#5. Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1078)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1071)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#6. Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:580)
       at java.lang.Thread.getAllStackTraces(Thread.java:522)
       at com.crashlytics.android.core.CrashlyticsController.writeSessionEvent(CrashlyticsController.java:1317)
       at com.crashlytics.android.core.CrashlyticsController.writeFatal(CrashlyticsController.java:1004)
       at com.crashlytics.android.core.CrashlyticsController.access$400(CrashlyticsController.java:67)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:319)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:312)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#7. ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:164)
       at java.lang.Thread.run(Thread.java:818)

#8. FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:423)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
       at java.lang.Thread.run(Thread.java:818)

#9. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#10. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#11. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#12. main
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418)
       at java.util.concurrent.FutureTask.get(FutureTask.java:176)
       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
       at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:312)
       at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:296)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

#13. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#14. Thread-139
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2053)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
       at com.google.android.gms.common.zza.zza(Unknown Source)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.start(Unknown Source)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
       at java.lang.reflect.Method.invoke(Method.java)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getInfo(AdvertisingInfoReflectionStrategy.java:106)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getAdvertisingId(AdvertisingInfoReflectionStrategy.java:76)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getAdvertisingInfo(AdvertisingInfoReflectionStrategy.java:66)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider.getAdvertisingInfoFromStrategies(AdvertisingInfoProvider.java:118)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider.access$000(AdvertisingInfoProvider.java:28)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider$1.onRun(AdvertisingInfoProvider.java:70)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#15. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

#16. FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:298)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:267)
       at java.lang.Thread.run(Thread.java:818)

#17. Queue
       at libcore.io.Posix.poll(Posix.java)
       at libcore.io.BlockGuardOs.poll(BlockGuardOs.java:195)
       at libcore.io.IoBridge.isConnected(IoBridge.java:238)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
       at libcore.io.IoBridge.connect(IoBridge.java:127)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:457)
       at java.net.Socket.connect(Socket.java:927)
       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
       at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
       at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
       at com.android.okhttp.Connection.connect(Connection.java:167)
       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209)
       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
       at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:352)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:341)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:259)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:454)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
       at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:2450)
       at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:2463)
       at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2542)
       at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2526)
       at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2512)
       at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.applyMultipartDataTo(AbstractAppSpiCall.java:108)
       at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.invoke(AbstractAppSpiCall.java:76)
       at io.fabric.sdk.android.services.settings.UpdateAppSpiCall.invoke(UpdateAppSpiCall.java:29)
       at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:204)
       at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:194)
       at io.fabric.sdk.android.Onboarding.performAutoConfigure(Onboarding.java:175)
       at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:112)
       at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
       at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
       at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
       at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)


```

**Comment by pawelDylag** [comment]
Hey @MBach 

It looks like the problem is with the `Notification` object. The system is unable to read it from the parcel sent to `ActivityManager` service. Could you please verify, that the same `notification` object gets displayed using Notification service on this phone? The truth is, that our SDK just lets your `notification` to pass through it, without modifying it. So the problem might be in the implementation of ActivityManager on the Wiko's ROM implementation, or it needs to be using different notification builder - like the one from support library. Can you try playing with it and tell me if something works? 

Regards, 
Paweł

**Comment by MBach** [comment]
I'll try to use the `NotificationCompat.Builder` but honestly, I have some doubts that it will change anything. The resulting `Notification` object created by `build()` only inherits from `Object` (not from an interface). And it's in Android since API level 1, so it's pretty robust in my humble opinion.

**Comment by croustibat** [comment]
Actually we are developping a bridge between React Native and the Estimote Proximity SDK. Everything works fine on Android API 24 and newer but we can't make it work on API 23 and lower.  
Are you aware of bugs on Android Marshmallow or something ?

Here is the import we use on our main module :
`
package io.matierenoire.bridge.estimote;

import android.app.Notification;
import android.app.PendingIntent;
import android.bluetooth.BluetoothAdapter;
import android.content.Context;
import android.content.Intent;
import android.provider.Settings;
import android.util.Log;
import android.support.v4.app.NotificationCompat;

import com.estimote.cloud_plugin.common.EstimoteCloudCredentials;
import com.estimote.internal_plugins_api.cloud.proximity.ProximityAttachment;
import com.estimote.proximity_sdk.proximity.ProximityObserver;
import com.estimote.proximity_sdk.proximity.ProximityObserverBuilder;
import com.estimote.proximity_sdk.proximity.ProximityZone;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.modules.core.RCTNativeAppEventEmitter;

import java.util.ArrayList;
import java.util.List;

import kotlin.Unit;
import kotlin.jvm.functions.Function1;
`

thank you for your help.

**Comment by MBach** [comment]
Hello,
Do you have any progress on this one? Can you confirm to us that beacon events are triggered on Android 6.0?

**Comment by pawelDylag** [comment]
Hey @MBach 

It's a little bit difficult for me to test this on Wiko Fever. I am unable to reproduce this on any phone available at our office (Android range 5.0-8.1, Samsung, Lg, Pixel, Huawei, Motorola, and some more).  Is this only happening on your Wiko Fever? Can you try building your own foreground service and launch it with the similar notifiaction? I need to make sure that this doesn't depend on Wiko's ROM.

Kind regards, 
Paweł

**Comment by MBach** [comment]
Hi @pawelDylag 
I haven't had yet the time to build my own foreground service, but I've tried a production build on an Sony Xperia E5 and it was not working neither. Have you tried on some Sony devices too?
Regards,

**Comment by pawelDylag** [comment]
Hey @MBach 

Tested on our Nexus 6 (6.0), and Sony Xperia F8331 (7.1) - works like a charm. Could you try launching our example app and check if it's working on your phones? Maybe there is something wrong with your app, and we're not looking for the problem at its core. I am still unable to reproduce this problem, but I will do anything to fix it if I'll make sure it comes from our SDK :)

Regards, 
Paweł

**Comment by MBach** [comment]
When you have foreground service activated, you can reproduce the crash when you remove the authorization in app settings:

`Fatal Exception: java.lang.RuntimeException: Unable to start service com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService@1583b54 with null: java.lang.IllegalArgumentException: null notification
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3696)
       at android.app.ActivityThread.-wrap21(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by pawelDylag** [comment]
Hey @MBach 

Thanks for this extremely useful info! Yes, I can reproduce it right now. I will dig deeper into it and will try to see if this is correlated with your previous problem. Potentially it may be caused by the system trying to recreate service, but the Notification is no more there. Will let you know about the results :)

Regards, 
Paweł

**Comment by MBach** [comment]
You can't imagine how much time I've spent on this problem...

**Comment by pawelDylag** [comment]
You must be a true hero, sir :) You deserve a cookie -> 🍪.

I tested everything and the fix is already waiting for the next release - disabling permissions won't result in crash.  I assume that this will be also a solution for your problem, but you will need to verify it on your Wiko phone, because we don't have it here :)

Regards, 
Paweł

**Comment by pawelDylag** [comment]
@MBach  - version `0.3.3` should be now available. You can try it out and let me know if your problem is solved :)

**Comment by MBach** [comment]
I don't have the crash anymore, nice one! However, I don't think it's normal to have the notification service still displayed on top. Shouldn't be desactivated automatically?

**Comment by pawelDylag** [comment]
We'll think about the best possible behaviour. For now it's important that it's not resulting in a crash :)
