### ISSUE TITLE
Exception involving com.estimote:mustard library

### ISSUE THREAD

**Issue by MarcoManca** [Estimote/Android-Proximity-SDK#22]
## Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** com.estimote:proximity-sdk:0.2.3 com.estimote:mustard:0.+

**Android devices affected:** Samsung Galaxy S5 SM-G900F

**Android OS version affected:** Android 6.0.1

**Beacon hardware version:** F3.3

## Description

Hi, 
I tried to install my application which uses proximity sdk on a device running android 7 and I have no problems. Now I tried to install the same on a samsung s5 with android 6.0.1 and I got the following exception caused by mustard library
:
 Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                      at android.app.ContextImpl.startActivity(ContextImpl.java:734)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:721)
                      at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
                      at com.estimote.mustard.rx_goodness.rx_activity_result.RxActivityResult.startActivityForResult(RxActivityResult.kt:31)
                      at com.estimote.mustard.rx_goodness.rx_activity_result.RxActivityResult.startActivityForResult$default(RxActivityResult.kt:28)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.spells.FulfillLocationPermissionRequirementSpell.fulfill(FulfillLocationPermissionRequirementSpell.kt:26)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard.checkAndFulfillLocationPermission(EstimoteRequirementsWizard.kt:26)
                      at com.estimote.mustard.rx_goodness.rx_requirements_wizard.EstimoteRequirementsWizard.fulfillRequirements(EstimoteRequirementsWizard.kt:19)
                      at hiis.isti.cnr.it.estimoteproximitydelegate.MainActivity.onCreate(MainActivity.java:91)

Line 91 of the MainActivity.java is the follpwing:

RequirementsWizardFactory.createEstimoteRequirementsWizard().fulfillRequirements(getApplicationContext(),new Function0<Unit>() {
                    @Override public Unit invoke() {
                        Log.d("app", "requirements fulfilled");
                        checkConfiguration();
                        return null;
                    }
                },
                // onRequirementsMissing
                new Function1<List<? extends Requirement>, Unit>() {
                    @Override public Unit invoke(List<? extends Requirement> requirements) {
                        TextView txtMsg = findViewById(R.id.txtMsg);
                        txtMsg.setText("Missing Requirements");

                        Log.e("app", "requirements missing: " + requirements);
                        return null;
                    }
                },
                // onError
                new Function1<Throwable, Unit>() {
                    @Override public Unit invoke(Throwable throwable) {
                        TextView txtMsg = findViewById(R.id.txtMsg);
                        txtMsg.setText("Missing Requirements");
                        Log.e("app", "requirements error: " + throwable);
                        return null;
                    }
                });

What do I have to modify?

Thank you,

best

Marco

**Comment by pawelDylag** [comment]
Hey @MarcoManca 

Thanks for reporting this. The problem is because of the `context` you pass to our `RequirementsCheckerWizard`. It needs to be a context of your current activity, because the `wizard` is trying to display dialogs to enable bluetooth, request permissions, and so. Can you try using your activity's context and let me know if that works? We will make sure this behaviour won't happen in the next release.

Regards, 
Paweł

**Comment by pawelDylag** [comment]
Hey @MarcoManca, 

in the version `0.2.1` of our Mustard library, the`RequirementWizard` needs `Activity` instead of `Context` as a parameter when creating. The problem should be no more. 

Also I added a section about `Mustard` itself to our [README](https://github.com/Estimote/Android-Proximity-SDK#checking-requirements-with-requirementswizard)

Regards, 
Paweł
