### ISSUE TITLE
 Bluetooth Low Energy scan failed with error code: 4

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-Proximity-SDK#37]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [Paste here the SDK version that you are using (like `0.1.0-alpha.6`)]

**Android devices affected:** [Paste here your Android device model/models that you are having problems with.]

**Android OS version affected:** [Android OS version (ex. `Oreo 8.0.0`)]

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

[Description of the issue]

**(Optional) Steps to reproduce:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

## Additional information
SDK VERSION 0.4.1
device: Samsung j7 prime (7.0 os version) 

```
Add here any logs you want to attach, or any other info, like pictures for example
``03-20 11:52:59.912 14982-14982/com.estimote.proximitycontent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.estimote.proximitycontent, PID: 14982
                                                                               io.reactivex.exceptions.UndeliverableException: java.lang.Exception: Bluetooth Low Energy scan failed with error code: 4
                                                                                   at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:573)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.observers.SerializedObserver.onError(SerializedObserver.java:155)
                                                                                   at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.onError(ObservableDebounceTimed.java:104)
                                                                                   at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.onError(ObservableRefCount.java:134)
                                                                                   at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.onError(ObservablePublish.java:184)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.onError(ObservableRefCount.java:134)
                                                                                   at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.onError(ObservablePublish.java:184)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:571)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                                                   at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.operators.observable.ObservableGroupBy$GroupByObserver.onError(ObservableGroupBy.java:137)
                                                                                   at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
                                                                                   at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
                                                                                   at com.estimote.proximity_sdk.monitoring.estimote_monitoring.secure.SecureEstimoteMonitor$startEstimoteSecureScanResolving$1$2.invoke(SecureEstimoteMonitor.kt:46)
                                                                                   at com.estimote.proximity_sdk.monitoring.estimote_monitoring.secure.SecureEstimoteMonitor$startEstimoteSecureScanResolving$1$2.invoke(SecureEstimoteMonitor.kt:20)
                                                                                   at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$notifyUserCallbacks$2.accept(ScanUseCase.kt:28)
                                                                                   at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$notifyUserCallbacks$2.accept(ScanUseCase.kt:8)
                                                                                   at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                   at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
                                                                                   at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
03-20 11:52:59.914 14982-14982/com.estimote.proximitycontent E/AndroidRuntime:     at com.estimote.scanning_plugin.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1.onScanFailed(PostLollipopEstimoteScanner.kt:30)
                                                                                   at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:532)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                                Caused by: java.lang.Exception: Bluetooth Low Energy scan failed with error code: 4
                                                                                   at com.estimote.scanning_plugin.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1.onScanFailed(PostLollipopEstimoteScanner.kt:30) 
                                                                                   at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:532) 
                                                                                   at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by pawelDylag** [comment]
Hello @rajeshkanna777 

Version `0.4.2` is now live - it now properly handles errors, so you shouldn't have any crashes from now on. Everything will be properly reported through `onErrorAction` :)

**Comment by GraceHuntley** [comment]
Just wanted to comment here as well. Error code 4 is still being thrown and unhandled in 0.4.2 sdk. Specifically for a samsung J7

**Comment by pawelDylag** [comment]
Hey guys, 

Pro tip to my future self - **always check if you rebased and merged feature branch to master before releasing the new version** 😆 
Sorry for this, the version `0.4.3` should contain all the changes ^^

Regards, 
Paweł
