### ISSUE TITLE
Crash if Bluetooth is disabled

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#4]
Hi,
I encountered crashes when I use Proximity SDK if I forgot to activate Bluetooth on my device.
Here is the stacktrace:

`Fatal Exception: java.lang.IllegalStateException: Cannot obtain BluetoothLeScanner instance. Ensure Bluetooth is enabled on your device
       at com.estimote.scanning_sdk.dagger.BluetoothModule.providesBluetoothLeScanner(BluetoothModule.kt:30)
       at com.estimote.scanning_sdk.dagger.BluetoothModule_ProvidesBluetoothLeScannerFactory.get(BluetoothModule_ProvidesBluetoothLeScannerFactory.java:31)
       at com.estimote.scanning_sdk.dagger.BluetoothModule_ProvidesBluetoothLeScannerFactory.get(BluetoothModule_ProvidesBluetoothLeScannerFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactoryFactory.get(ScannerModule_ProvideScannerFactoryFactory.java:30)
       at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactoryFactory.get(ScannerModule_ProvideScannerFactoryFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactory.get(ScannerModule_ProvideScannerFactory.java:30)
       at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactory.get(ScannerModule_ProvideScannerFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.scanning_sdk.dagger.UseCaseModule_ProvideIBeaconScanUseCaseFactory.get(UseCaseModule_ProvideIBeaconScanUseCaseFactory.java:46)
       at com.estimote.scanning_sdk.dagger.UseCaseModule_ProvideIBeaconScanUseCaseFactory.get(UseCaseModule_ProvideIBeaconScanUseCaseFactory.java:12)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.scanning_sdk.dagger.PacketProviderModule_ProvidesPacketProviderFactory.get(PacketProviderModule_ProvidesPacketProviderFactory.java:105)
       at com.estimote.scanning_sdk.dagger.PacketProviderModule_ProvidesPacketProviderFactory.get(PacketProviderModule_ProvidesPacketProviderFactory.java:22)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.scanning_sdk.api.EstimoteBluetoothScannerFactory_MembersInjector.injectMembers(EstimoteBluetoothScannerFactory_MembersInjector.java:40)
       at com.estimote.scanning_sdk.api.EstimoteBluetoothScannerFactory_MembersInjector.injectMembers(EstimoteBluetoothScannerFactory_MembersInjector.java:9)
       at com.estimote.scanning_sdk.dagger.DaggerEstimoteScanningSdkComponent.inject(DaggerEstimoteScanningSdkComponent.java:269)
       at com.estimote.scanning_sdk.dagger.Dagger$Companion.injectInTo(Dagger.kt:28)
       at com.estimote.scanning_sdk.api.EstimoteBluetoothScannerFactory.<init>(EstimoteBluetoothScannerFactory.kt:30)
       at com.estimote.proximity_sdk.dagger.MonitorModule.provideEstimoteBluetoothScannerFactory(MonitorModule.kt:21)
       at com.estimote.proximity_sdk.dagger.MonitorModule_ProvideEstimoteBluetoothScannerFactoryFactory.get(MonitorModule_ProvideEstimoteBluetoothScannerFactoryFactory.java:24)
       at com.estimote.proximity_sdk.dagger.MonitorModule_ProvideEstimoteBluetoothScannerFactoryFactory.get(MonitorModule_ProvideEstimoteBluetoothScannerFactoryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.proximity_sdk.dagger.MonitorModule_ProvideEstimoteMonitorFactory.get(MonitorModule_ProvideEstimoteMonitorFactory.java:42)
       at com.estimote.proximity_sdk.dagger.MonitorModule_ProvideEstimoteMonitorFactory.get(MonitorModule_ProvideEstimoteMonitorFactory.java:12)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.proximity_sdk.dagger.ProximityObserverModule_ProvideEstimoteProximityUseCaseFactory.get(ProximityObserverModule_ProvideEstimoteProximityUseCaseFactory.java:45)
       at com.estimote.proximity_sdk.dagger.ProximityObserverModule_ProvideEstimoteProximityUseCaseFactory.get(ProximityObserverModule_ProvideEstimoteProximityUseCaseFactory.java:12)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.proximity_sdk.dagger.ProximityObserverModule_ProvideProximityObserverFactory.get(ProximityObserverModule_ProvideProximityObserverFactory.java:32)
       at com.estimote.proximity_sdk.dagger.ProximityObserverModule_ProvideProximityObserverFactory.get(ProximityObserverModule_ProvideProximityObserverFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.estimote.proximity_sdk.proximity.ProximityObserverFactory_MembersInjector.injectMembers(ProximityObserverFactory_MembersInjector.java:31)
       at com.estimote.proximity_sdk.proximity.ProximityObserverFactory_MembersInjector.injectMembers(ProximityObserverFactory_MembersInjector.java:7)
       at com.estimote.proximity_sdk.dagger.DaggerProximitySdkComponent$ProximityObserverComponentImpl.inject(DaggerProximitySdkComponent.java:182)
       at com.estimote.proximity_sdk.dagger.Dagger$Companion.injectInTo(Dagger.kt:31)
       at com.estimote.proximity_sdk.proximity.ProximityObserverFactory.create(ProximityObserverFactory.kt:23)
       at com.medium.reactnative.estimote.RNEstimoteModule.start(RNEstimoteModule.java:129)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:762)`

I think you should write a small listener which can activate / desactivate Bluetooth and also shows a popup to the user in order to activate Bluetooth.

**Comment by pawelDylag** [comment]
Hey @MBach 

Thank you for reporting that - yes, we know about this issue - it's already fixed and is waiting for the next release :) 
Will notify you when it will be live :)

Regards, 
Paweł

**Comment by MBach** [comment]
Hello @pawelDylag 

Great news! Looking forward to hearing from you

**Comment by pawelDylag** [comment]
Hey @MBach 
Fixed in `0.1.0-alpha.6`. Also, checkout the [CHANGELOG](https://github.com/Estimote/Android-Proximity-SDK/blob/master/CHANGELOG.md) to see how to deal with breaking changes, and how to use our `RequirementsWizard` And don't forget to see an [example app](https://github.com/Estimote/Android-Proximity-SDK/tree/master/example/ProximityApp)!

Regards, 
Paweł
