### ISSUE TITLE
Crash with too many proximity zones

### ISSUE THREAD

**Issue by OscarCanek** [Estimote/Android-Proximity-SDK#55]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.5.1

**Android devices affected:** Moto G Play

**Android OS version affected:** 6.0.1

**Beacon hardware version:** F3.3

## Description

I was testing the SDK and found when I created a lot of proximity zones on one observer the app crashes. I created 50 proximity zones.
 
- What is the maximun number of zones I can create with the SDK?

The code I used is the following:

```C#
var zoneBuilder = Observer.ZoneBuilder();
            OnEnterZoneHandler en = new OnEnterZoneHandler();
            OnChangeZoneHandler ch = new OnChangeZoneHandler();
            OnExitZoneHandler ex = new OnExitZoneHandler();
            bool first = true;
            foreach (var range in ranges)
            {
                ProximityZones.Add(zoneBuilder
                .ForAttachmentKeyAndValue(first ? "AuparNotificationZone" : key, first ? "Always" : value)
                .InCustomRange(range)
                .WithOnEnterAction(en)
                .WithOnChangeAction(ch)
                .WithOnExitAction(ex)
                .Create());

                Log.Debug("app", $"Proximity all ready to go! - Zone range {range} ");
            }

            Observer.AddProximityZones(ProximityZones);
```

The exception is thrown just reading when reading the first beacon.

**Expected behavior:**: the app should not crash

**Actual behavior:** the app crashes

## Additional information
```
AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.474 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.479 W/art     (27233): Throwing OutOfMemoryError "Could not allocate JNI Env"
06-11 15:56:09.480 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.480 W/System.err(27233): java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
06-11 15:56:09.480 W/System.err(27233): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
06-11 15:56:09.480 W/System.err(27233): 	at android.os.Handler.handleCallback(Handler.java:746)
06-11 15:56:09.480 W/System.err(27233): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-11 15:56:09.480 W/System.err(27233): 	at android.os.Looper.loop(Looper.java:148)
06-11 15:56:09.480 W/System.err(27233): 	at android.app.ActivityThread.main(ActivityThread.java:5459)
06-11 15:56:09.480 W/System.err(27233): 	at java.lang.reflect.Method.invoke(Native Method)
06-11 15:56:09.480 W/System.err(27233): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
06-11 15:56:09.481 W/System.err(27233): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-11 15:56:09.481 W/System.err(27233): Caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
06-11 15:56:09.482 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.490 W/System.err(27233): 	at java.lang.Thread.nativeCreate(Native Method)
06-11 15:56:09.490 W/System.err(27233): 	at java.lang.Thread.start(Thread.java:1063)
06-11 15:56:09.490 W/System.err(27233): 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
06-11 15:56:09.490 W/System.err(27233): 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1556)
06-11 15:56:09.490 W/System.err(27233): 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:310)
06-11 15:56:09.490 W/System.err(27233): 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:543)
06-11 15:56:09.490 W/System.err(27233): 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:642)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:146)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.schedulers.IoScheduler$EventLoopWorker.schedule(IoScheduler.java:230)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:135)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:111)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.completable.CompletableSubscribeOn.subscribeActual(CompletableSubscribeOn.java:38)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.Completable.subscribe(Completable.java:1635)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.completable.CompletableObserveOn.subscribeActual(CompletableObserveOn.java:34)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.Completable.subscribe(Completable.java:1635)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.Completable.subscribe(Completable.java:1701)
06-11 15:56:09.490 W/System.err(27233): 	at com.estimote.analytics_plugin.proximity.EstimoteProximityAnalyticsReporter.reportStartMonitoringForIdentifier(EstimoteProximityAnalyticsReporter.kt:62)
06-11 15:56:09.490 W/System.err(27233): 	at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$sendProximityUsageMetrics$1.apply(ProximityObservationUseCase.kt:65)
06-11 15:56:09.490 W/System.err(27233): 	at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$sendProximityUsageMetrics$1.apply(ProximityObservationUseCase.kt:18)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:102)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onComplete(FlowableFlatMap.java:670)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:120)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:63)
06-11 15:56:09.490 W/System.err(27233): 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
06-11 15:56:09.491 W/System.err(27233): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-11 15:56:09.491 W/System.err(27233): 	... 7 more
06-11 15:56:09.504 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.506 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.521 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.539 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
06-11 15:56:09.552 E/NativeCrypto(27233): AppData::create pipe(2) failed: Too many open files
```

**Comment by pawelDylag** [comment]
Hey @OscarCanek 

Can you try disabling analytics via calling method `.withAnalyticsReportingDisabled()` on your `ProximityObserver` builder?  My guess is that creating so many zones just kills our internal analytics buffering mechanism. 

Cheers, 
Paweł

**Comment by OscarCanek** [comment]
I tested disabling analytics using `.withAnalyticsReportingDisabled()` and this avoids the crash, this will be fixed any time soon?

**Comment by pawelDylag** [comment]
Yes, we'll fix that - I have added this to our backlog :) Should be released in the upcoming releases. 

Paweł
