### ISSUE TITLE
Crash when toggling Airplane mode

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#6]
Hi,

Using latest Proximity SDK (alpha 6), it seems that I sometimes have hard crash of my App when activating / deactivating airplane mode.

Here's the stacktrace grabbed with Crashlytics:

`Fatal Exception: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$stopMonitoringWhenDisposed$1$2.accept(ProximityObservationUseCase.kt:54)
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$stopMonitoringWhenDisposed$1$2.accept(ProximityObservationUseCase.kt:16)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
       at com.crashlytics.android.core.TrimmedThrowableData.<init>(TrimmedThrowableData.java:19)
       at com.crashlytics.android.core.CrashlyticsController.writeSessionEvent(CrashlyticsController.java:1293)
       at com.crashlytics.android.core.CrashlyticsController.writeFatal(CrashlyticsController.java:1004)
       at com.crashlytics.android.core.CrashlyticsController.access$400(CrashlyticsController.java:67)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:319)
       at com.crashlytics.android.core.CrashlyticsController$7.call(CrashlyticsController.java:312)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.net.ConnectException: Failed to connect to /192.168.10.100:8080
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225)
       at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:198)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.AuthorizationHeaderInterceptor.intercept(HttpInterceptors.kt:26)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.UserAgentHeaderInterceptor.intercept(HttpInterceptors.kt:16)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.ContentTypeHeaderInterceptor.intercept(HttpInterceptors.kt:9)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
       at okhttp3.RealCall.execute(RealCall.java:69)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.net.ConnectException: Network is unreachable
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
       at java.net.Socket.connect(Socket.java:586)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
       at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:198)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.AuthorizationHeaderInterceptor.intercept(HttpInterceptors.kt:26)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.UserAgentHeaderInterceptor.intercept(HttpInterceptors.kt:16)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.estimote.cloud_plugin.common.ContentTypeHeaderInterceptor.intercept(HttpInterceptors.kt:9)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
       at okhttp3.RealCall.execute(RealCall.java:69)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
       at io.reactivex.Single.subscribe(Single.java:2707)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.IllegalStateException: invoke(...) must not be null
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCaseKt$sam$Consumer$c4447207.accept(ProximityObservationUseCase.kt)
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$stopMonitoringWhenDisposed$1$2.accept(ProximityObservationUseCase.kt:54)
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$stopMonitoringWhenDisposed$1$2.accept(ProximityObservationUseCase.kt:16)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

Is there a way to prevent these crash by putting some try and catch somewhere?

**Comment by pawelDylag** [comment]
Hey @MBach 
Thank you for reporting this issue - this is definitely to be fixed in the upcoming releases :) 
I remind you that we are still in `alpha` stage, so such cases may sometimes appear for now. We will handle all of them until the version `1.0.0` :)

Regards, 
Paweł

**Comment by MBach** [comment]
Hello @pawelDylag 

I know this is alpha stage but it might be useful to list them here. Oh and by the way, do you have any roadmap to 1.0.0?

Regards

**Comment by MBach** [comment]
Hello,
Are there any progress on this one?
Also, sometimes I have this stacktrace, but maybe it's another bug, I don't know:

`Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:206)
       at com.estimote.scanning_sdk.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$1.cancel(PostLollipopEstimoteScanner.kt:29)
       at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:122)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:583)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:509)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:307)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:100)
       at com.estimote.scanning_sdk.api.use_cases.RxScanHandler.stop(RxScanHandler.kt:10)
       at com.estimote.proximity_sdk.monitoring.estimote_monitoring.SimpleEstimoteMonitor$startEstimoteLocationScan$1$2$1.cancel(SimpleEstimoteMonitor.kt:50)
       at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:122)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.dispose(ObservablePublish.java:156)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:217)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:80)
       at io.reactivex.internal.operators.observable.ObservableRefCount$DisposeTask.run(ObservableRefCount.java:219)
       at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:30)
       at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:20)
       at io.reactivex.disposables.ReferenceDisposable.dispose(ReferenceDisposable.java:43)
       at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.dispose(ObservableRefCount.java:151)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
       at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:86)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:100)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:217)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:80)
       at com.estimote.proximity_sdk.monitoring.EstimoteMonitor$Handler.stop(EstimoteMonitor.kt:14)
       at com.estimote.proximity_sdk.proximity.ProximityObservationUseCase$stopMonitoringWhenDisposed$1$1$1.cancel(ProximityObservationUseCase.kt:50)
       at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:122)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:100)
       at com.estimote.proximity_sdk.proximity.RxHandler.stop(RxHandler.kt:9)
       at com.estimote.proximity_sdk.telemetry_reporter.TelemetryProximityObserverWrapper$WrapperHandler.stop(TelemetryProximityObserverWrapper.kt:47)
       at io.matierenoire.bridge.estimote.RNEstimoteModule.stopMonitorDevice(RNEstimoteModule.java:178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:163)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:760)`

**Comment by pawelDylag** [comment]
Hey @MBach 

Version `0.2.2` is now live. This issue should be no more a problem. Please verify it on your side before we close this issue :)
Please let us know about any problems you have with our SDK :) 
Here is a cookie for you for posting this issue -> 🍪  !!!

Regards, 
Paweł

**Comment by MBach** [comment]
Hi @pawelDylag 

It's fixed I guess, I don't have any more crashes when I'm toggling Airplane mode on or off.

I'd prefer to have free Beacons 📧
