### ISSUE TITLE
Android background monitoring service

### ISSUE THREAD

**Issue by kisukesnow** [Estimote/Android-Proximity-SDK#72]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    *[X] My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    *[X] My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    *[X] My Android device/devices have bluetooth enabled
    *[X] My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [0.6.2]

**Android devices affected:** [ Motorola Moto G5 ]
** [ Samsung J2 ]

**Android OS version affected:** [Android 7.0]
** [Android 6.0.1]

**Beacon hardware version:** [4.13.2] 

## Description
I am using Android Java to create a Plugin for Unity3D. The plugin looks for beacons on foreground without a notification and on background with a notification when the app is paused. Everything works finr until I try to stop the background service in the OnDestroy method using Android's Task Manager. The service stops, it no longer check for beacons but it leaves the "scanning" notification active and when the app tries to start the service again, it crashes.  

**Expected behavior:** [Stopping the service OnDestroy and cancel the notification]

**Actual behavior:** [The service stops but the notification appears again after a moment]

## Additional information
`````
Main Activity 
 @Override
    public void onDestroy() {
        if (pointsTotal > 0) {
            SaveToPlayerPref();
        }
        notificationManager.stopMonitoring();
        super.onDestroy();
    }

  protected void onPause(){

//This variable checks the requirements wizards
        if(readyToMonitor){
            notificationManager.startMonitoring();
        }
        super.onPause();

    }

Notification Manager

 public void startMonitoring() {
  Notification scanningNotification= new NotificationCompat.Builder(context, "content_channel")
                    .setSmallIcon(android.R.drawable.ic_dialog_info)
                    .setContentTitle(title)
                    .setContentText(text)
                    .setContentIntent(PendingIntent.getActivity(context, 0,
                            new Intent(context, UnityPlayer.currentActivity.getClass()), PendingIntent.FLAG_ONE_SHOT))
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                    .build();

           proximityObserver =
                    new ProximityObserverBuilder(context, cloudCredentials)
                            .withOnErrorAction(new Function1<Throwable, Unit>() {
                                @Override
                                public Unit invoke(Throwable throwable) {
                                    Log.e("app", "proximity observer error: " + throwable);
                                    return null;
                                }
                            })
                            .withBalancedPowerMode()
                            .withScannerInForegroundService(scanningNotification)
                            .withEstimoteSecureMonitoringDisabled()
                            .withTelemetryReportingDisabled()
                            .build();

        venueZone =
                proximityObserver.zoneBuilder()
                        .forTag("location")
                        .inCustomRange(1.5)
                        .withOnEnterAction(new Function1<ProximityContext, Unit>() {
                            @Override public Unit invoke(ProximityContext proximityContext) {
                                OnEnterArea(proximityContext,notificationId);
                                return null;
                            }
                        })
                        .withOnExitAction(new Function1<ProximityContext, Unit>() {
                            @Override
                            public Unit invoke(ProximityContext proximityContext) {
                                notificationManager.cancel(notificationId);
                                OnExitArea(proximityContext, exitAreaID);
                                return null;
                            }
                        })
                        .create();


        proximityObserver.addProximityZone(venueZone);
        proximityObserverHandler = proximityObserver.start();
    }

public void stopMonitoring(){

        if(proximityObserverHandler != null){
            proximityObserverHandler.stop();
        }

        notificationManager.cancelAll();


    }





Error Log at starting again the service: 
07-19 16:52:38.430 19635-19635/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eleven.ProyectoLocacionCC, PID: 19635
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2017.4.0f1
    Device model      : motorola Moto G (5) Plus
    Device fingerprint: motorola/potter_n/potter_n:7.0/NPNS25.137-92-10/12:user/release-keys
    
    Caused by: java.lang.RuntimeException: Unable to start service com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService@81ecceb with Intent { cmp=com.eleven.ProyectoLocacionCC/com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService (has extras) }: kotlin.UninitializedPropertyAccessException: lateinit property serviceHelper has not been initialized
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3335)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property serviceHelper has not been initialized
        at com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService.showNotification(PacketProviderWrapperService.kt:82)
        at com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService.onStartCommand(PacketProviderWrapperService.kt:32)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3318)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

**Comment by kisukesnow** [comment]
Hi @pawelDylag 
I ended up doing my own service and is working great!

Thank you

**Comment by chlegou** [comment]
@kisukesnow could you please provide us with a complete working solution? i didn't managed it to work with services.

**Comment by saadmutahar** [comment]
@kisukesnow Can you please help me out that how to get work with creating our own service. Thank you.
