### ISSUE TITLE
Unable to start scanner on this Android version (28)

### ISSUE THREAD

**Issue by Cooxter** [Estimote/Android-Proximity-SDK#77]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.6.2

**Android devices affected:** Pixel 2

**Android OS version affected:** 9.0.0

**Beacon hardware version:** J1.6

## Description

App crashes on start when running on a device with Android version 28.

## Additional information
```
08-14 17:17:44.455 21015-21242/ie.blackbear.soundscapes E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-17
    Process: ie.blackbear.soundscapes, PID: 21015
    java.lang.IllegalStateException: Unable to start scanner on this Android version (28)
        at com.estimote.scanning_plugin.packet_provider.scanner.AlwaysErrorEstimoteScaner.scan(AlwaysErrorEstimoteScaner.kt:13)
        at com.estimote.scanning_plugin.packet_provider.use_cases.EstimoteSecureScanUseCase.run(EstimoteSecureScanUseCase.kt:20)
        at com.estimote.scanning_plugin.packet_provider.EstimotePacketProvider.provideEstimoteSecure(EstimotePacketProvider.kt:100)
        at com.estimote.scanning_plugin.api.EstimoteBluetoothScanner$estimoteSecureScan$1.invoke(EstimoteBluetoothScanner.kt:46)
        at com.estimote.scanning_plugin.api.EstimoteBluetoothScanner$estimoteSecureScan$1.invoke(EstimoteBluetoothScanner.kt:10)
        at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$scanForPacketsAccordingToSettings$1.apply(ScanUseCase.kt:22)
        at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$scanForPacketsAccordingToSettings$1.apply(ScanUseCase.kt:8)
...
```

**Comment by edysolisaritec** [comment]
Same error for Estimote SDK version: 1.0.1

**Comment by pawelDylag** [comment]
Hello guys!

It's all about support for Android Pie. We'll add it in the upcoming days :)

**Comment by sam-element** [comment]
???
