### ISSUE TITLE
Android 10 is not supported.

### ISSUE THREAD

**Issue by CakeWalker1337** [Estimote/Android-Proximity-SDK#97]
Hi there!
I am using Estimote android proximity sdk v1.0.3 and have a trouble with using beacon scanner on android 10 device (Google Pixel 3). I couldn't found any mentions about android 10 support, so, please, give any information (approximate date of new release or something like this) about supporting of Android 10. Thanks a lot!

**Comment by Vallle** [comment]
Same issue for me. Android Studio suggested that we could bump android proximity SDK to v1.0.4 but same problem there.

`    java.lang.IllegalStateException: Unable to start scanner on this Android version (29)
        at com.estimote.scanning_plugin.packet_provider.scanner.AlwaysErrorEstimoteScaner.scan(AlwaysErrorEstimoteScaner.kt:13)
        at com.estimote.scanning_plugin.packet_provider.use_cases.EstimoteSecureScanUseCase.run(EstimoteSecureScanUseCase.kt:20)
        at com.estimote.scanning_plugin.packet_provider.EstimotePacketProvider.provideEstimoteSecure(EstimotePacketProvider.kt:102)
        at com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperService.provideEstimoteSecure(PacketProviderWrapperService.kt:81)
        at com.estimote.scanning_plugin.api.EstimoteBluetoothScanner$estimoteSecureScan$1.invoke(EstimoteBluetoothScanner.kt:46)
        at com.estimote.scanning_plugin.api.EstimoteBluetoothScanner$estimoteSecureScan$1.invoke(EstimoteBluetoothScanner.kt:10)
        at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$scanForPacketsAccordingToSettings$1.apply(ScanUseCase.kt:22)
        at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$scanForPacketsAccordingToSettings$1.apply(ScanUseCase.kt:8)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onNext(ObservableRefCount.java:208)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.internal.operators.observable.ObservableReplay$UnboundedReplayBuffer.replay(ObservableReplay.java:553)
        at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.replay(ObservableReplay.java:401)
        at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.onNext(ObservableReplay.java:366)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
        at com.estimote.scanning_plugin.packet_provider.service.PacketProviderWrapperServiceHelper$createServiceConnection$1.onServiceConnected(PacketProviderWrapperServiceHelper.kt:41)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by cskjetne** [comment]
Add this dependancy to force a newer version of the scanning plugin;

`implementation 'com.estimote:scanning-plugin:0.25.4'
`

**Comment by josephnolasco** [comment]
> Add this dependancy to force a newer version of the scanning plugin;
> 
> `implementation 'com.estimote:scanning-plugin:0.25.4' `

This resolved the issue. Thank you

**Comment by Poberro** [comment]
Proximity SDK version 1.0.5 has this fixed.
